base:
  project: breast_classified
  pkg_list_fname: pkg_list.txt
  random_state: 0

data_load:
  SLIDE_DIR: data
  TRAIN_CSV_PATH: label/breast.csv
  SLIDE_FILE_EXTENSION: .svs
  INPUT_SIZE: [1558, 1558, 3]
  RESIZE_RATIO: 0.2
  SLIDE_READER: openslide
  DEBUG_PATH: 
  NUM_CLASSES: 2
  BATCH_SIZE: 1
  X_Y_Batch_Path: datapreprocessed
  data_dir: data
